config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'daily_logs#index'

  resources :users do
    resources :pets, only: [:new, :create, :edit , :update]
      resources :gallery_images, only: [:index]
  end

  #管理に関するルーティング
  resources :daily_logs

  # 記事に関するルーティング
  resources :articles
  get 'checks/:id', to: 'checks#check', as: 'check'
  post 'checks/:id/revert_check', to: 'checks#revert_check', as: 'create_revert_check'
  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  has_many :checks, dependent: :destroy
  has_many :users, through: :checks
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :title, length: { maximum: 20 }
    validates :content
    validates :user_id
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    # 月間ランキング用の記事
    @ranking_articles = Article.where('created_at >= ?', 1.month.ago)
                               .order(views_count: :desc)
                               .limit(10)
  
    # カテゴリIDがパラメータとして存在する場合、そのカテゴリに属する記事を取得
    if params[:category_id].present?
      @articles = Article.where(category_id: params[:category_id])
    else
      @articles = Article.all
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: '記事が作成されました。'
    else
      render :new
    end
  end

  def show
    @article.increment!(:views_count)
  end

  def edit
    @article.user == current_user
  end
  
  def update
    if @article.update(article_params)
      return redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.user == current_user
      @article.destroy
      redirect_to articles_path, notice: '記事が削除されました。'
    else
      redirect_to articles_path, alert: '他のユーザーの記事は削除できません。'
    end
  end

  private
  def article_params
    params.require(:article).permit(
      :category_id,
      :title,
      :content,
      :image
    ).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find_by(id: params[:id])
    unless @article
      redirect_to new_user_session_path, alert: 'ログインが必要です。'
    end
  end

  def check_user
    redirect_to articles_path, alert: '権限がありません。' unless @article.user == current_user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render "shared/header" %>

<div class="post-article-form">
  <%= form_with(model: @article, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :title, '記事名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-article-title", placeholder: "記事名" %>
    <p><%= f.label :content, '記事内容' %><span>（必須）</span></p>
    <%= f.text_area :content, class:"new-article-content", placeholder: "記事内容" %>
    <p><%= f.label :image, 'アイキャッチ画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <%= f.submit "投稿", class:"new-article-submit_btn" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= render "shared/header" %>
  
<div class="main-contents">
  <div class="articles">
    <% @articles.each do |article| %>
      <div class="article" id=<%= article.id%>>
        <div class="article-overview">
          <%= link_to check_path(article) do %>
            <p class="article-title">
              <%= article.title%>
            </p>
            <p class="article-content">
              <%= article.content%>
            </p>
          <% end %>
          <div class="article-information">
            <p class="article-post-date">
              <%= article.created_at.strftime("%Y年 %m月 %d日") %>
            </p>
            <div class="article-check">
              <% if user_signed_in? && Check.where(user_id: current_user.id, article_id: article.id).exists? %>
                <div class="article-check-button" data-id=<%= article.id %>>
                  既読
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <%= image_tag article.image.variant(resize_to_fill: [400, 400]), class: "article-image" %>
      </div>
    <% end %>
  </div>

    <div class="ranking">
    <p class="ranking-name">
      月間ランキング
    </p>
    <div class="ranking-articles">
      <% @ranking_articles.each_with_index do |r_article, i| %>
      <div class="ranking-article">
          <p class="weekly-rank">
            <%= i+1 %>
          </p>
          <div class="ranking-overview">
            <%= link_to check_path(r_article) do %>
              <%= image_tag r_article.image.variant(resize_to_fill: [400, 400]), class: "ranking-article-image" %>
              <div class="ranking-article-title">
                <%= r_article.title%>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/articles/new.html.erb
<%= render "shared/header" %>

<div class="post-article-form">
  <%= form_with(model: @article, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    
    <p><%= f.label :category_id, 'カテゴリー' %><span>（必須）</span></p>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "カテゴリーを選択してください"}, {class: "new-article-category"} %>

    <p><%= f.label :title, '記事名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-article-title", placeholder: "記事名" %>

    <p><%= f.label :content, '記事内容' %><span>（必須）</span></p>
    <%= f.text_area :content, class:"new-article-content", placeholder: "記事内容" %>

    <p><%= f.label :image, 'アイキャッチ画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <div id="previews"></div>
    
    <%= f.submit "投稿", class:"new-article-submit_btn" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<%= render "shared/header" %>
<div class="show-article">
  <p class="show-article-title">
    <%= @article.title %>
  </p>
  <p class="show-article-post-date">
    <%= @article.created_at.strftime("%Y年 %m月 %d日") %>
  </p>
  <%= image_tag @article.image.variant(resize: '500x500'), class: "show-article-image" %>
  <p class="show-article-content">
    <%= @article.content %>
  </p>
</div>

<% if @article.user == current_user %>
  <div class="change-article">
    <div class="edit-article">
      <%= link_to "編集", edit_article_path(@article), class:"edit-btn" %>
    </div>
    <div class="delete-article">
      <%= link_to '削除', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: 'delete-btn' %>
    </div>
  </div>
<% end %>

<div class="return-toppage">
  <%= link_to "トップページへ戻る", articles_path, class:"return-btn" %>
</div>