config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'daily_logs#index'

  resources :users do
    resources :pets, only: [:new, :create, :edit , :update]
      resources :gallery_images, only: [:index]
  end

  #管理に関するルーティング
  resources :daily_logs

  # 記事に関するルーティング
  resources :articles
  get 'checks/:id', to: 'checks#check', as: 'check'
  post 'checks/:id/revert_check', to: 'checks#revert_check', as: 'create_revert_check'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  has_many :checks, dependent: :destroy
  has_many :users, through: :checks
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :title, length: { maximum: 20 }
    validates :content
    validates :user_id
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/daily_log.rb
class DailyLog < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  has_many :gallery_images
  has_one_attached :image

  validates :date, presence: true
  validates :food_intake, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :water_intake, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :toilet_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :exercise_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
  belongs_to :user
  belongs_to :daily_log, optional: true

  has_one_attached :image
  
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  has_many :daily_logs, dependent: :destroy#destroyは無くすかも
  has_many :health_checks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets
  has_many :daily_logs
  has_many :gallery_images
  has_many :checks, dependent: :destroy
  has_many :articles, through: :checks

  validates :name, presence: true
end

app/models/user_pet.rb
class UserPet
  include ActiveModel::Model
  attr_accessor :email, :password, :password_confirmation, :name, :pet_name, :pet_age, :pet_weight, :update_context, :user

  validates :email, presence: true, unless: -> { update_context }
  validates :password, presence: true, confirmation: true, unless: -> { update_context }
  validates :password_confirmation, presence: true, unless: -> { update_context }
  validates :name, presence: true
  validates :pet_name, presence: true
  validates :pet_age, numericality: { only_integer: true, greater_than: 0 }
  validates :pet_weight, numericality: { greater_than_or_equal_to: 0 }
  
  def save
    return false unless valid?

    if update_context
      # 更新処理
      user.update(name: name)
      pet = user.pets.first 
      pet.update(name: pet_name, age: pet_age, weight: pet_weight)
      true
    else
      # 新規作成処理
      user = User.new(email: email, password: password, password_confirmation: password_confirmation, name: name)
      if user.save
        user.pets.create(name: pet_name, age: pet_age, weight: pet_weight)
        return user
      else
        user.errors.full_messages.each { |msg| errors.add(:base, msg) }
        return false
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    # 月間ランキング用の記事
    @ranking_articles = Article.where('created_at >= ?', 1.month.ago)
                               .order(views_count: :desc)
                               .limit(10)
  
    # カテゴリIDがパラメータとして存在する場合、そのカテゴリに属する記事を取得
    if params[:category_id].present?
      @articles = Article.where(category_id: params[:category_id])
    else
      @articles = Article.all
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: '記事が作成されました。'
    else
      render :new
    end
  end

  def show
    @article.increment!(:views_count)
  end

  def edit
    @article.user == current_user
  end
  
  def update
    if @article.update(article_params)
      return redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.user == current_user
      @article.destroy
      redirect_to articles_path, notice: '記事が削除されました。'
    else
      redirect_to articles_path, alert: '他のユーザーの記事は削除できません。'
    end
  end

  private
  def article_params
    params.require(:article).permit(
      :category_id,
      :title,
      :content,
      :image
    ).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find_by(id: params[:id])
    unless @article
      redirect_to new_user_session_path, alert: 'ログインが必要です。'
    end
  end

  def check_user
    redirect_to articles_path, alert: '権限がありません。' unless @article.user == current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_article, only: [:check, :revert_check]

  def check
    if user_signed_in?
      Check.find_or_create_by(user_id: current_user.id, article_id: @article.id)
    end
    redirect_to article_path(@article)
  end

  def revert_check
    if user_signed_in?
      check = Check.find_by(user_id: current_user.id, article_id: @article.id)
      check.destroy if check
    end
    head :no_content
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/daily_logs_helper.rb
module DailyLogsHelper
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetHealthDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model && model.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: model.errors.count,
                 resource: model.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header"> 
  <div class="logo">
    <%= link_to 'Pet News', articles_path, class: 'archivo-black-regular' %>
  </div>
  <div class="header-btn">
    <% if user_signed_in? %>
      <%= link_to '記事を投稿する', new_article_path, class: "post-article-btn" %>
    <% end %>
    <%= link_to 'トップページに戻る', root_path, class: "post-article-btn2" %>
  </div>
  <div class="menu-bar">
    <ul class="menu-elements">
      <% food_category = Category.find_by(name: "食事") %>
      <% exercise_category = Category.find_by(name: "運動") %>
      <% vaccine_category = Category.find_by(name: "予防接種") %>
      <% disease_category = Category.find_by(name: "病気・ケガ") %>
      <% other_category = Category.find_by(name: "その他") %>
    
      <li><%= link_to '全体記事', articles_path, class: "menu-item" %></li>
      <li><%= link_to '食事', articles_path(category_id: food_category.id), class: "menu-item" if food_category %></li>
      <li><%= link_to '運動', articles_path(category_id: exercise_category.id), class: "menu-item" if exercise_category %></li>
      <li><%= link_to '予防接種', articles_path(category_id: vaccine_category.id), class: "menu-item" if vaccine_category %></li>
      <li><%= link_to '病気・ケガ', articles_path(category_id: disease_category.id), class: "menu-item" if disease_category %></li>
      <li><%= link_to 'その他', articles_path(category_id: other_category.id), class: "menu-item" if other_category %></li>
    </ul>
  </div>
</div>

app/views/shared/_loading.erb
<div id="loading">
    <p>Loading...</p>
    <div id="loading-screen"></div>
</div>

app/views/shared/_nav_meny.erb
<nav>
    <button id="menu-open" class="btn-menu">
        <svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
            <title>メニューを開く</title>
            <path clip-rule="evenodd" d="m4.25 8c0-.41421.33579-.75.75-.75h14c.4142 0 .75.33579.75.75s-.3358.75-.75.75h-14c-.41421 0-.75-.33579-.75-.75zm0 4c0-.4142.33579-.75.75-.75h14c.4142 0 .75.3358.75.75s-.3358.75-.75.75h-14c-.41421 0-.75-.3358-.75-.75zm.75 3.25c-.41421 0-.75.3358-.75.75s.33579.75.75.75h14c.4142 0 .75-.3358.75-.75s-.3358-.75-.75-.75z" fill-rule="evenodd"/>
        </svg>
    </button>
    <div id="menu-panel">
        <button id="menu-close" class="btn-menu">
            <svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                <title>メニューを閉じる</title>
                <path clip-rule="evenodd" d="m7.53033 6.46967c-.29289-.29289-.76777-.29289-1.06066 0s-.29289.76777 0 1.06066l4.46963 4.46967-4.46963 4.4697c-.29289.2929-.29289.7677 0 1.0606s.76777.2929 1.06066 0l4.46967-4.4696 4.4697 4.4696c.2929.2929.7677.2929 1.0606 0s.2929-.7677 0-1.0606l-4.4696-4.4697 4.4696-4.46967c.2929-.29289.2929-.76777 0-1.06066s-.7677-.29289-1.0606 0l-4.4697 4.46963z" fill-rule="evenodd"/>
            </svg>
        </button>
        <ul class="menu-list">

            <li><%= link_to 'トップページ', root_path %></li>
            <% if user_signed_in? %>
             <li><%= link_to current_user.name, edit_user_registration_path, class: "user-nickname" %></li>
             <li><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout" %></li>
             <li><%= link_to '記録項目', new_daily_log_path %></li>
             <li><%= link_to 'ギャラリー', user_gallery_images_path(current_user) %></li>
            <% if @daily_logs.present? %>
              <li><%= link_to 'カレンダー', daily_log_path(@daily_logs.last) %></li>
            <% end %>
            <% else %>
              <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
              <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <% end %>
              <li><%= link_to 'ニュース', articles_path %></li>
        </ul>
    </div>
</nav>